name: Delete Preview App
on:
  pull_request:
    types: [closed]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  delete_preview_app:
    runs-on: ubuntu-latest
    environment:
      name: pr-${{ github.event.number }}
      url: pr-${{ github.event.number }}-phx-tools.fly.dev
    steps:
      - uses: actions/checkout@v3
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}
